allowBuilds:
  core-js-pure: false
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@storybook/addon-docs@10.5.5"
  - "@storybook/addon-onboarding@10.5.5"
  - "@storybook/addon-vitest@10.5.5"
  - "@storybook/builder-vite@10.5.5"
  - "@storybook/csf-plugin@10.5.5"
  - "@storybook/nextjs-vite@10.5.5"
  - "@storybook/react-dom-shim@10.5.5"
  - "@storybook/react-vite@10.5.5"
  - "@storybook/react@10.5.5"
  - eslint-plugin-storybook@10.5.5
  - storybook@10.5.5
